[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
colb_finance = "GGxsxxRJAcvNVA6SRb9WeLdkZmXMsAE62tF73U7J8mjG"
colb_private_factory = "HxQhUN65mxvfhDm1UpPiaL4Xa833uGWyT2snTXGG1ZSi"
colb_private_pool = "7wSRuQ1thJzxWmWrsukGJCBz5pE48hCczUpNeJoHw5WH"
colb_swap = "EQbygpUkAveiHQgyGpVtfJ7k22JyTReG1etBUZPZshYs"
colb_usc = "Bt35z2yWaM1Lbs68pNLy7wCCdEfG5xCPaaoXTCwpMmhw"
whitelist = "DMkMJucBK2QV32Tsbsb9HuUv59CBa5wr1tcah3AEKYV2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
